# Generated by Django 4.2 on 2023-06-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_date',
            field=models.DateField(max_length=4, null=True),
        ),
    ]
